-- Expansão do banco para um Admin no estilo da versão Lovable.
-- Preserva as tabelas e os dados existentes.

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_date date not null default current_date,
  end_date date,
  status text not null default 'active'
    check (status in ('upcoming', 'active', 'finished')),
  created_at timestamptz not null default now()
);

create unique index if not exists one_active_season
on public.seasons ((status))
where status = 'active';

create table if not exists public.championships (
  id bigint generated by default as identity primary key,
  name text not null,
  season_id bigint references public.seasons(id) on delete set null,
  status text not null default 'planned'
    check (status in ('planned', 'finished')),
  played_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.matches
  add column if not exists match_type text not null default 'friendly'
    check (match_type in ('friendly', 'championship'));

alter table public.matches
  add column if not exists season_id bigint
    references public.seasons(id) on delete set null;

alter table public.matches
  add column if not exists championship_id bigint
    references public.championships(id) on delete set null;

alter table public.matches
  add column if not exists played_at timestamptz;

update public.matches
set played_at = coalesce(played_at, created_at, now())
where played_at is null;

alter table public.matches
  alter column played_at set default now();

alter table public.matches
  alter column played_at set not null;

alter table public.seasons enable row level security;
alter table public.championships enable row level security;

grant select on public.seasons, public.championships
to anon, authenticated;

grant insert, update, delete on public.seasons, public.championships
to authenticated;

drop policy if exists "seasons readable by everyone" on public.seasons;
create policy "seasons readable by everyone"
on public.seasons
for select
to public
using (true);

drop policy if exists "admins manage seasons" on public.seasons;
create policy "admins manage seasons"
on public.seasons
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "championships readable by everyone" on public.championships;
create policy "championships readable by everyone"
on public.championships
for select
to public
using (true);

drop policy if exists "admins manage championships" on public.championships;
create policy "admins manage championships"
on public.championships
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.seasons (name, start_date, status)
select 'Temporada 1', current_date, 'active'
where not exists (
  select 1 from public.seasons
);

notify pgrst, 'reload schema';
